export default {
  login: "soumikmofficial",
  id: 88224962,
  node_id: "MDQ6VXNlcjg4MjI0OTYy",
  avatar_url: "https://avatars.githubusercontent.com/u/88224962?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/soumikmofficial",
  html_url: "https://github.com/soumikmofficial",
  followers_url: "https://api.github.com/users/soumikmofficial/followers",
  following_url:
    "https://api.github.com/users/soumikmofficial/following{/other_user}",
  gists_url: "https://api.github.com/users/soumikmofficial/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/soumikmofficial/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/soumikmofficial/subscriptions",
  organizations_url: "https://api.github.com/users/soumikmofficial/orgs",
  repos_url: "https://api.github.com/users/soumikmofficial/repos",
  events_url: "https://api.github.com/users/soumikmofficial/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/soumikmofficial/received_events",
  type: "User",
  site_admin: false,
  name: "soumik",
  company: null,
  blog: "",
  location: "kolkata, India",
  email: null,
  hireable: null,
  bio: "Just a guy to code and chill with.",
  twitter_username: "soumikmofficial",
  public_repos: 14,
  public_gists: 20,
  followers: 56,
  following: 6,
  created_at: "2021-07-31T06:17:54Z",
  updated_at: "2021-09-05T20:00:13Z",
};
